json.id @user.id
json.email @user.email
json.name @user.name
json.person @user.person
json.city @user.city
json.phone @user.phone
json.inn @user.inn
json.role @user.role
json.legal_address @user.legal_address
json.actual_address @user.actual_address
json.kpp @user.kpp
json.bank_name @user.bank_name
json.curr_account @user.curr_account
json.corr_account @user.corr_account
json.bik @user.bik
json.ogrn @user.ogrn
json.note @user.note